# Config file for automatic testing at travis-ci.org
dist: bionic
language: python
python:
  - 3.8
  - 3.7

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install .

# Command to run tests, e.g. python setup.py test
script:
  # test with pytest
  - make test
  # generate the docs
  - make build-docs

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Put in settings as a secure variable
  keep_history: true
  on:
    branch: master
  verbose: true
  local_dir: docs/
