# Config file for automatic testing at travis-ci.org
dist: bionic
language: python
python:
  - 3.8
  - 3.7

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install --user poetry
  - poetry install

# Command to run tests, e.g. python setup.py test
script:
  # test with pytest
  - make test
