name: docs

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Check out master
        uses: actions/checkout@v2
      - name: Check out gh-pages
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages
      - name: Build documentation
        uses: ammaraskar/sphinx-action@0.4
        with:
          docs-folder: docs/
          build-command: make html
          pre-build-command: python -m pip install --upgrade pip && pip install poetry==1.1.5 && poetry config virtualenvs.create false && poetry install
      - name: Commit documentation changes
        run: |
          cp -r docs/build/html/* gh-pages/
          cd gh-pages
          touch .nojekyll
          git config --local user.name github-actions
          git config --local user.email github-actions@github.com
          git add .
          git commit -m "Updated documentation" -a || true
          git push
